USE [Library]
GO

/****** Object:  Table [dbo].[book]    Script Date: 09.09.2021 0:23:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[book](
	[íd] [int] NOT NULL,
	[name] [nchar](100) NOT NULL,
	[author_id] [int] NOT NULL,
 CONSTRAINT [PK_book_1] PRIMARY KEY CLUSTERED 
(
	[íd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [unique_author] UNIQUE NONCLUSTERED 
(
	[íd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[book]  WITH CHECK ADD  CONSTRAINT [FK_book_author] FOREIGN KEY([author_id])
REFERENCES [dbo].[author] ([id])
GO

ALTER TABLE [dbo].[book] CHECK CONSTRAINT [FK_book_author]
GO

